FROM python:3.10-slim

WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install dependencies
RUN pipenv install --system --deploy

COPY src /app/src
COPY models /app/models

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
