FROM python:3.10-slim

WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install dependencies
RUN pipenv install --system --deploy

COPY src /app/src

EXPOSE 8501

CMD ["streamlit", "run", "src/streamlit_app.py"]
