version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: earthquake_prediction_base:latest

  api:
      build: 
        context: .
        dockerfile: Dockerfile.api
      ports:
        - "8000:8000"
      volumes:
        - ./models:/app/models
        - ./static:/app/static  # Add this line
      environment:
        - STATIC_DIR=/app/static  # Add this line
      depends_on:
        - base
        - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    depends_on:
      - base

  prefect:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    ports:
      - "4200:4200"
    depends_on:
      - base

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - base
      - api

volumes:
  models:
  mlruns: