name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Run linter
      run: make lint
    - name: Check formatting
      run: pipenv run black . --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Run tests
      run: make test

  build-and-push:
    runs-on: ubuntu-latest
    needs: [code-quality, test]
    strategy:
      matrix:
        dockerfile: [Dockerfile.api, Dockerfile.streamlit, Dockerfile.mlflow, Dockerfile.prefect]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./${{ matrix.dockerfile }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/earthquake-prediction-${{ matrix.dockerfile }}:latest

  format:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Format with black
      run: make format
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply automatic formatting changes"
        branch: ${{ github.head_ref }}